### ISSUE TITLE
CV2 Error !_src.empty()

### ISSUE THREAD

**Issue by nulleve** [ogkalu2/comic-translate#120]
Tested on two different machines, both running AMD CPUs and GPUs.
Both machines running Windows 24H2 (26120.1350) Dev Insider Edition.

The following error occurs while running both Automatic and Manual seemingly during the `Detect Text Boxes` and `OCR` runtime.
```
Traceback (most recent call last):
  File "C:\Users\Evelynne\Downloads\comic-translate-main\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Evelynne\Downloads\comic-translate-main\pipeline.py", line 186, in batch_process
    blk_list = self.block_detector_cache.detect(image)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Evelynne\Downloads\comic-translate-main\modules\detection.py", line 26, in detect
    combined = self.combine_results(bble_detec_result, txt_seg_result, txt_detect_result)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Evelynne\Downloads\comic-translate-main\modules\detection.py", line 51, in combine_results
    content_bboxes = detect_content_in_bbox(crop)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Evelynne\Downloads\comic-translate-main\modules\detection.py", line 210, in detect_content_in_bbox
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
```

Occasionally it seems to run one time before running the error above, however if it runs it just returns and image similar to the following attached, hopefully this is a simple issue I'm overlooking.

![](https://github.com/user-attachments/assets/eb6553fd-c9a7-4361-96ad-376448b557bd)

**Comment by notimp** [comment]
https://stackoverflow.com/questions/52676020/imread-returns-none-violating-assertion-src-empty-in-function-cvtcolor-er

try renaming files? ;)

**Comment by notimp** [comment]
You can also do a

pip list -o

to see what your outdated dependencies are. (outdated = good in this instance), here are mine:

![dependencies comic transate](https://github.com/user-attachments/assets/a510442e-6c08-4111-aa9c-6701e9f4b293)

If your version numbers match, we can be sure, that the dependencies we use have the same version numbers and dont fail, because some of them might have updated and changed something in its code that devs havent reacted to so far - and that your install failed because of that.

Will not be applicable as a troubleshooting step for years into the future, but since I installed my installation on a windows 11 system just a few weeks ago, and everything is working -- currently its an easy way to compare what you have installed, and what a person has installed that has the program running without issues.

Only do that if you have ensured, that your comics file names and paths dont include special characters, that the python coding could get hung up on. (bad coding.)

**Comment by nulleve** [comment]
Thanks for the help, the overflow post seemed possible as the original file names were `20240729104144_21b41baf0e48766c2790b0751dfec250_IMAG01_1.jpg` and similar however after changing them around to `KoreanTest1.jpg` and numbered so-forth the issue still persisted. Moving them straight into the working directory seemed to have no affect either, so testing with verbosity afterwards it seems like the `image` is accurately being found. (This is the case as well when it does fully complete with the automatic mode; i.e with the bugged black-box images)
![{3D1CCF79-578B-4FAD-B7BA-21F2ABA3550A}](https://github.com/user-attachments/assets/e6f247f7-cbdf-41f1-9c11-64489be61a35)

While my `opencv-python` version seems to be the proper version;
![{D06023F6-C295-41E7-B2A6-ECE30DB2707B}](https://github.com/user-attachments/assets/41aa26a3-3a37-4612-a098-ba3bb0bcb7ec)

A few of my dependencies were more up to date so I downgraded them to your versions, which also seemed to run into the same persistent error prior.
![{7A3D81FD-207C-4CD4-9EE6-653C33D285AA}](https://github.com/user-attachments/assets/91209e81-f267-4a18-b1e4-ab1eea543c6e)

From the list above, it seems like I am clearly missing several dependencies compared to your image (on two different PCs oddly enough), so I ran through and ran `pip install --force-install -v` for every package you seemed to have shown above to get the proper versions.

![{54567689-A67A-4155-8F6F-9EB17F272A5E}](https://github.com/user-attachments/assets/801ffc55-aa9f-4e78-b4a8-d91d280d4e07)

This seems to have failed as well, which now has me endlessly confused haha, if someone wants to give this a run with the same korean images they are going to be listed here below.

![20240311210248_8a5caa95f3e25852f4a35fdca61de9a6_IMAG01_2](https://github.com/user-attachments/assets/70107ae7-f05c-4e54-9072-cd4f5acb115b)
![20240729104144_21b41baf0e48766c2790b0751dfec250_IMAG01_5](https://github.com/user-attachments/assets/de86df13-a8d1-4552-90b3-2fddac5fcedf)

**Comment by notimp** [comment]
Missing dependencies, I wouldnt worry about, I also installed pdf support (see one of the recent tickets in here) and installed the specific nvidia driver packages the install instructions hinted at.

I'll try to convert your images to english now. Give me a sec.

**Comment by notimp** [comment]
Yeah, I coould convert both without issues (i used google vision OCR and google translate to translate the text). Therefore filenames werent the problem, neither were the images.

![359338965-70107ae7-f05c-4e54-9072-cd4f5acb115b_translated](https://github.com/user-attachments/assets/ace37adf-41c4-43b2-9cd7-b428afdc5780)
![359338973-de86df13-a8d1-4552-90b3-2fddac5fcedf_translated](https://github.com/user-attachments/assets/24ca4609-578c-47ba-a013-a084c6deed89)

All I can do is to point you to: https://github.com/ogkalu2/comic-translate/issues/113

to see if a reinstall fixes it, if not - wait for an actual dev. :)

**Comment by Alexamenus** [comment]
Rolling for developer reply.
I've had the exact same issue too.

**Comment by Alexamenus** [comment]
This error is due to to a missing dependency that was not specified in the requirements.txt and or an incompatible versions of python.

**Comment by ogkalu2** [comment]
@nulleve 
Is this still an issue with the latest update ?

**Comment by nulleve** [comment]
> @nulleve Is this still an issue with the latest update ?

Sorry I am no-longer on Windows to test this, I'll let my friend know who still uses the application to test it out and let you know if any issues persist :)

**Comment by ogkalu2** [comment]
No worries. Thanks. And sorry for the late reply.

**Comment by Alexamenus** [comment]
> @nulleve Is this still an issue with the latest update ?

yes it is very much still a problem. Not with with every single image but i've encountered it at least 5 times today. In fact I just got it again while typing this 

An error occurred:
error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


Traceback:
Traceback (most recent call last):
  File "C:\Users\daneb\Desktop\comic-translate-main\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\daneb\Desktop\comic-translate-main\pipeline.py", line 175, in batch_process
    blk_list = self.block_detector_cache.detect(image)
  File "C:\Users\daneb\Desktop\comic-translate-main\modules\detection.py", line 26, in detect
    combined = self.combine_results(bble_detec_result, txt_seg_result, txt_detect_result)
  File "C:\Users\daneb\Desktop\comic-translate-main\modules\detection.py", line 44, in combine_results
    adjusted_bboxes = get_inpaint_bboxes(bbox, self.image)
  File "C:\Users\daneb\Desktop\comic-translate-main\modules\detection.py", line 75, in get_inpaint_bboxes
    content_bboxes = detect_content_in_bbox(crop)
  File "C:\Users\daneb\Desktop\comic-translate-main\modules\detection.py", line 238, in detect_content_in_bbox
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by ogkalu2** [comment]
@Alexamenus 
How about now ?

**Comment by Alexamenus** [comment]
> @Alexamenus How about now ?

At a cursory glance when trying with a singular image that i previously had the error with, yes I did not encounter the error.
However with the new build I encountered a new error that prevents rendering more than one at a time in in the project.

An error occurred:
AttributeError: 'ComicTranslate' object has no attribute 'update_image_history'

Traceback:
Traceback (most recent call last):
  File "C:\Users\user\Desktop\comic-translate-main\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\user\Desktop\comic-translate-main\pipeline.py", line 236, in batch_process
    self.main_page.update_image_history(image_path, inpaint_input_img)
AttributeError: 'ComicTranslate' object has no attribute 'update_image_history'

**Comment by ogkalu2** [comment]
@Alexamenus 
Ah. This is fixed now

**Comment by Alexamenus** [comment]
> @Alexamenus Ah. This is fixed now

ah i think that completely borked it. it's translating the images fine, but now none of the translated images are viewable in the application 


Traceback (most recent call last):
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 346, in <lambda>
    worker.signals.result.connect(lambda result: QtCore.QTimer.singleShot(0, lambda: result_callback(result)))
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 569, in <lambda>
    lambda result: self.display_image_from_loaded(result, index),
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 595, in display_image_from_loaded
    self.display_image(index, switch_page)
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 669, in display_image
    self.load_image_state(file_path)
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 630, in load_image_state
    self.set_cv2_image(cv2_image)
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 611, in set_cv2_image
    self.undo_group.activeStack().push(command)
  File "C:\Users\user\Desktop\comic-translate-main\app\ui\commands\image.py", line 23, in redo
    cv2_img = self.get_img(file_path, current_index)
  File "C:\Users\user\Desktop\comic-translate-main\app\ui\commands\image.py", line 88, in get_img
    cv2_img = cv2.imread(self.image_history[file_path][current_index])
AttributeError: 'SetImageCommand' object has no attribute 'image_history'

**Comment by Alexamenus** [comment]
> @Alexamenus Try again
tried it with a different set of images, yeah its still happening.

**Comment by ogkalu2** [comment]
> > @Alexamenus Try again
> 
> tried it with a different set of images, yeah unfortunately it's still happening.

Are you sure. The error shouldn't be the same anymore. What's the error ?

**Comment by Alexamenus** [comment]
> > > @Alexamenus Try again
> > 
> > 
> > tried it with a different set of images, yeah unfortunately it's still happening.
> 
> Are you sure. The error shouldn't be the same anymore. What's the error ?

Traceback (most recent call last):
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 346, in <lambda>
    worker.signals.result.connect(lambda result: QtCore.QTimer.singleShot(0, lambda: result_callback(result)))
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 569, in <lambda>
    lambda result: self.display_image_from_loaded(result, index),
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 595, in display_image_from_loaded
    self.display_image(index, switch_page)
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 669, in display_image
    self.load_image_state(file_path)
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 630, in load_image_state
    self.set_cv2_image(cv2_image)
  File "C:\Users\user\Desktop\comic-translate-main\comic.py", line 611, in set_cv2_image
    self.undo_group.activeStack().push(command)
  File "C:\Users\user\Desktop\comic-translate-main\app\ui\commands\image.py", line 23, in redo
    cv2_img = self.get_img(file_path, current_index)
  File "C:\Users\user\Desktop\comic-translate-main\app\ui\commands\image.py", line 88, in get_img
    cv2_img = cv2.imread(self.image_history[file_path][current_index])
AttributeError: 'SetImageCommand' object has no attribute 'image_history'

The image in the timeline doesn't change and cmd windows spits that out.

**Comment by ogkalu2** [comment]
@Alexamenus 

You downloaded the update?

Open app\ui\commands\image.py. what does line 88 say ?

**Comment by Alexamenus** [comment]
> @Alexamenus
> 
> You downloaded the update?
> 
> Open app\ui\commands\image.py. what does line 88 say ?

    cv2_img = cv2.imread(self.image_history[file_path][current_index])

**Comment by ogkalu2** [comment]
@Alexamenus 

Change self.image_history to self.ct.image_history

**Comment by Alexamenus** [comment]
> @Alexamenus
> 
> Change self.image_history to self.ct.image_history
> 
> No idea why it didn't reflect for you.

yeah that's weird, but i think that did do the trick, thanks.
