### ISSUE TITLE
New update with saving the project

### ISSUE THREAD

**Issue by TaunT** [ogkalu2/comic-translate#143]
@ogkalu2 First of all, thanks for the continued work on the functionality!

Some questions:

1) There is still not enough functionality to be able to manually clean/correct the image with an external program. The project is saved in "сtpr" - is this a zip archive? I unpacked it, edited the image and packed it again) But not everyone can do this. And why use msgpack inside if everything is archived anyway, can't you just use json?

2) BUG When loading a project or navigating through images, some blocks break their condition, apparently they are not always saved.
![image](https://github.com/user-attachments/assets/e91f2e3c-ac56-4adc-99c0-218ae35d007c)

3) BUG 
If you save a project while working on an image (digitization has taken place, but there is no rendering), then when loading the project one image is broken and is not displayed. Although it is in the archive of the saved project. Now the project is broken. Apparently, the link to the temporary file is saved, and not to the main image.
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\9EF8~1\\AppData\\Local\\Temp\\tmpf0wgw7uf\\unique_images\\RCO003.jpg'
```
![image](https://github.com/user-attachments/assets/dfcb60e3-a390-44a8-b365-a485e1c640b0)

I created this temporary directory and put the file there. It was displayed inside the program, but for some reason the blocks were from the first image.
![image](https://github.com/user-attachments/assets/1b05ed8f-b2cc-4dba-947d-7c5d3d245e7d)

Another observation - when I started working with the second image and saved it, the third image became broken, that is, when saving, the next one breaks

3) there is still not enough highlighting in the top menu of the last action, on which step we are now

4) there are not enough navigation buttons between blocks. This is very useful at the stage of automatic block creation, to find "parasitic" extra blocks in the picture, which are simply part of the picture. Well, and then it is convenient to switch.

**Comment by lawrenz1** [comment]
> There is still not enough functionality to be able to manually clean/correct the image with an external program. The project is saved in "сtpr" - is this a zip archive? I unpacked it, edited the image and packed it again) But not everyone can do this.

I think you can export as zip, cbz, cb7, pdf, epub format which external programs can read and then import in the same format once you are done

**Comment by TaunT** [comment]
@lawrenz1 You didn't get it) the point was about a new feature - saving a project by a manager - with blocks, recognized text, translation, rendered text, all fonts with their size and color.
![image](https://github.com/user-attachments/assets/2f206bc2-eea6-4bae-889e-7f2e64a182c1)

**Comment by TaunT** [comment]
@ogkalu2 The tool for clearing filled segments has become worse. Previously, it simply erased the part you moved it over, but now it erases a small square block, so that the letter is exposed entirely. But I only needed to remove a little excess coloring.

**Comment by ogkalu2** [comment]
Just wanted to say i've seen this. I'll work on it in my free time. Very busy now.

**Comment by ogkalu2** [comment]
> @ogkalu2 The tool for clearing filled segments has become worse. Previously, it simply erased the part you moved it over, but now it erases a small square block, so that the letter is exposed entirely. But I only needed to remove a little excess coloring.
> 
> upd: The new mode of the "erase brush strokes" tool is very bad! Please roll back the change.

I didn't change how clearing filled segments work though ?
What's wrong with the new erase ?

**Comment by TaunT** [comment]
After the step "text segment" there are many separate red rectangles. Previously, when using the "erase tool" it was possible to erase part of the rectangle, but now it is deleted at once

**Comment by ogkalu2** [comment]
> After the "text segment" step, there are many separate red rectangles. 

Yes but that has been the case for..months now? Since I changed how segmentation works and inpainting became much better. If you choose to have segmentation be automatic by pressing the button, it's small rectangles and there's nothing I can really do about that. Manually drawing the strokes still return brush strokes.

>Previously, when using the "erase tool", it was possible to erase part of the rectangle, but now it is deleted entirely, even if it is slightly touched. If the corner of the square of the filled letter goes to the border of the bubble, then previously it was possible to erase this corner, but now the entire letter is deleted and it must be re-painted manually.

Okay. I'll look into that

**Comment by TaunT** [comment]
Here is an example, when you go a little on the letters and a large block is immediately cleared
https://github.com/user-attachments/assets/ebf288c4-b6ff-4e3a-87bd-c64ec1fc681a

**Comment by ogkalu2** [comment]
> Here is an example, when you go a little on the letters and a large block is immediately cleared
> 
>  default.mp4

This has been fixed now

**Comment by ogkalu2** [comment]
> @ogkalu2 First of all, thanks for the continued work on the functionality!
> 
> Some questions:
> 
> 1. There is still not enough functionality to be able to manually clean/correct the image with an external program. The project is saved in "сtpr" - is this a zip archive? I unpacked it, edited the image and packed it again) But not everyone can do this. And why use msgpack inside if everything is archived anyway, can't you just use json?
> 2. BUG When loading a project or navigating through images, some blocks break their condition, apparently they are not always saved.
>    ![image](https://private-user-images.githubusercontent.com/1741557/370192957-e91f2e3c-ac56-4adc-99c0-218ae35d007c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTg5MDgsIm5iZiI6MTczMDE1ODYwOCwicGF0aCI6Ii8xNzQxNTU3LzM3MDE5Mjk1Ny1lOTFmMmUzYy1hYzU2LTRhZGMtOTljMC0yMThhZTM1ZDAwN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMjMzNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzVjZGVhNTc3ZDNmMmJjNzdiZmYzZjVjODdhYzAxOGY0NDllMjZhMDE5ZmEwYTI2ZGZmYzhiMTEyM2FjZTYxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.acNnQPSuSsti4kYUs-v3p5TDkc6N1Un38t7G3nHrkfM)
> 3. BUG
>    If you save a project while working on an image (digitization has taken place, but there is no rendering), then when loading the project one image is broken and is not displayed. Although it is in the archive of the saved project. Now the project is broken. Apparently, the link to the temporary file is saved, and not to the main image.
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\9EF8~1\\AppData\\Local\\Temp\\tmpf0wgw7uf\\unique_images\\RCO003.jpg'
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/1741557/370248937-dfcb60e3-a390-44a8-b365-a485e1c640b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTg5MDgsIm5iZiI6MTczMDE1ODYwOCwicGF0aCI6Ii8xNzQxNTU3LzM3MDI0ODkzNy1kZmNiNjBlMy1hMzkwLTQ0YTgtYjM2NS1hNDg1ZTFjNjQwYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMjMzNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JhYTk4MzNkNTQ2NDk0ZDliM2I0ZWQ1YmIyNTA1ZDk2Nzk2YjRjNzM1ZDU5ODMxN2Q1ZmVkMWVmM2VlMmRkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gUclHccqxzArHAAvL269bEbbiPZIhf8bYt55q6BkC3c)
> 
> I created this temporary directory and put the file there. It was displayed inside the program, but for some reason the blocks were from the first image. ![image](https://private-user-images.githubusercontent.com/1741557/370252797-1b05ed8f-b2cc-4dba-947d-7c5d3d245e7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTg5MDgsIm5iZiI6MTczMDE1ODYwOCwicGF0aCI6Ii8xNzQxNTU3LzM3MDI1Mjc5Ny0xYjA1ZWQ4Zi1iMmNjLTRkYmEtOTQ3ZC03YzVkM2QyNDVlN2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMjMzNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2UzNzliNzYxMjlkMjM2ZjVmMGE4YjhjYTgyODE2MTAwMGEyMDVjNWRkZjU5YTBjNDg4OGRlY2IyZTYyZWUyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3AlgpEHJj3a-0hC3A3q_vspwyvLU1KNOVvz-ny25xlY)
> 
> Another observation - when I started working with the second image and saved it, the third image became broken, that is, when saving, the next one breaks
> 
> 3. there is still not enough highlighting in the top menu of the last action, on which step we are now
> 4. there are not enough navigation buttons between blocks. This is very useful at the stage of automatic block creation, to find "parasitic" extra blocks in the picture, which are simply part of the picture. Well, and then it is convenient to switch.

Can you try creating and loading new projects and see if bugs 2 and 3 still persist ?

**Comment by TaunT** [comment]
@ogkalu2 The second bug is still there. Here is the project file (changed to zip to upload) - I load it, three crooked blocks. I align them, save, load again - they have the old size.
[
[RCO123.zip](https://github.com/user-attachments/files/17552115/RCO123.zip)
](url)

![image](https://github.com/user-attachments/assets/b9b2a629-f2d1-4168-8e6a-d592c941f1c0)

**Comment by TaunT** [comment]
the third bug is fixed, thanks!

**Comment by ogkalu2** [comment]
> the third bug is fixed, thanks!

Alright. Can you send me an Image that causes this issue so I can do my own testing.

**Comment by TaunT** [comment]
Ok) But it doesn't depend on the picture, I have this on any of them.

![RCO123](https://github.com/user-attachments/assets/fbde9679-2de4-46e7-af15-4b257221715c)

**Comment by ogkalu2** [comment]
@TaunT 
Bug 2 has been fixed now. It works backwards so old projects should load correctly now

**Comment by ogkalu2** [comment]
> Ok) But it doesn't depend on the picture, I have this on any of them.
> 
> ![RCO123](https://private-user-images.githubusercontent.com/1741557/381228726-fbde9679-2de4-46e7-af15-4b257221715c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzU3MDAsIm5iZiI6MTczMDQzNTQwMCwicGF0aCI6Ii8xNzQxNTU3LzM4MTIyODcyNi1mYmRlOTY3OS0yZGU0LTQ2ZTctYWYxNS00YjI1NzIyMTcxNWMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDFUMDQzMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGZjODNjY2IzOGYyNTQxNGU0MDgxZDkzMDg5MWFlNmVjMDY5N2I2M2QzNjg4OGNlNjljZDZiMWVlNWRhOTE2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FUgw-p0D8JafAMbbyhF8qRkXULOX6VUc_cFOtrdrKGw)

This has been fixed now. It also works backwards so old projects should load correctly now

**Comment by ogkalu2** [comment]
For your first question. Originally this used yaml and saved all the images directly to file but that was godawfully slow so i looked for the fastest thing i could use without having to set up a separate prototype file and that was message pack. It was much faster but still too slow for my liking. Eventually i moved to saving the images in a folder instead (and only the in memory images to file) which increased speed a lot but by then i saw no need to change file formats.

**Comment by TaunT** [comment]
@ogkalu2 Thank you very much! The only bug that is still bothering me is this one https://github.com/ogkalu2/comic-translate/issues/107
I tried to fix it myself, but it didn't work

**Comment by ogkalu2** [comment]
> @ogkalu2 Thank you very much! The only bug that is still bothering me is this one #107 I tried to fix it myself, but it didn't work

Fixed
