### ISSUE TITLE
New nonsense, bold font stopped saving :(

### ISSUE THREAD

**Issue by TaunT** [ogkalu2/comic-translate#174]
The project contains text highlighted in bold. When saving the project itself and reopening it, everything is fine - this bold font is in place.

![image](https://github.com/user-attachments/assets/9241ca16-e482-4540-a8b3-2a7fe2bc7a2a)

 But if you export it to an image, then all the text is the same without highlighting

![image](https://github.com/user-attachments/assets/0e833b77-cc62-4ba0-89cc-b3cdd6e3d6d3)

**Comment by ogkalu2** [comment]
I think this has been fixed as well. Can you try this again ?

**Comment by TaunT** [comment]
@ogkalu2 It's gotten worse, now no saved project opens at all, an error occurs
```
Traceback (most recent call last):
  File "c:\comic-translate\comic-translate-TaunT\comic.py", line 453, in <lambda>
    worker.signals.result.connect(lambda result: QtCore.QTimer.singleShot(0, lambda: result_callback(result)))
  File "c:\comic-translate\comic-translate-TaunT\comic.py", line 1374, in <lambda>
    lambda result: self.display_image_from_loaded(result, index, switch_page=False),
  File "c:\comic-translate\comic-translate-TaunT\comic.py", line 750, in display_image_from_loaded
    self.display_image(index, switch_page)
  File "c:\comic-translate\comic-translate-TaunT\comic.py", line 825, in display_image
    self.load_image_state(file_path)
  File "c:\comic-translate\comic-translate-TaunT\comic.py", line 791, in load_image_state
    self.image_viewer.load_state(state['viewer_state'])
  File "c:\comic-translate\comic-translate-TaunT\app\ui\canvas\image_viewer.py", line 821, in load_state
    x, y, w, h = text_block['block'].xywh
  File "c:\comic-translate\comic-translate-TaunT\modules\utils\textblock.py", line 57, in xywh
    x1, y1, x2, y2 = self.xyxy
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by ogkalu2** [comment]
> @ogkalu2 It's gotten worse, now no old saved project opens at all, an error occurs
> 
> ```
> Traceback (most recent call last):
>   File "c:\comic-translate\comic-translate-TaunT\comic.py", line 345, in <lambda>
>     worker.signals.result.connect(lambda result: QtCore.QTimer.singleShot(0, lambda: result_callback(result)))
>   File "c:\comic-translate\comic-translate-TaunT\comic.py", line 1216, in <lambda>
>     lambda result: self.display_image_from_loaded(result, index, switch_page=False),
>   File "c:\comic-translate\comic-translate-TaunT\comic.py", line 594, in display_image_from_loaded
>     self.display_image(index, switch_page)
>   File "c:\comic-translate\comic-translate-TaunT\comic.py", line 668, in display_image
>     self.load_image_state(file_path)
>   File "c:\comic-translate\comic-translate-TaunT\comic.py", line 634, in load_image_state
>     self.image_viewer.load_state(state['viewer_state'])
>   File "c:\comic-translate\comic-translate-TaunT\app\ui\canvas\image_viewer.py", line 821, in load_state
>     x, y, w, h = text_block['block'].xywh
>   File "c:\comic-translate\comic-translate-TaunT\modules\utils\textblock.py", line 57, in xywh
>     x1, y1, x2, y2 = self.xyxy
> TypeError: cannot unpack non-iterable NoneType object
> ```

Fixed this. Try again

**Comment by TaunT** [comment]
Projects now open, thank you. But with bold font it's still not so good.
I also noticed that if the whole block is bold, then it looks right on export, but if only some words, then it doesn't stand out.

![image](https://github.com/user-attachments/assets/2a271bfa-b851-4508-a4ff-77642c193a84)

![image](https://github.com/user-attachments/assets/fa024dad-7473-4dad-aff0-85a79dd1d7cd)

I don't know, maybe it's the font's features...
But it's strange that the highlighted words after export are slightly different, but just a little bit, not as noticeable as in the program window.

**Comment by ogkalu2** [comment]
Yeah that's strange. 
I noticed the project file you sent this time wasn't ballooned in size. Is that no longer a problem or was it just a problem with a specific file ?

Also, how are you trying to export this to an image (the button for a the single file download or the one that exports everything to a zip?). Can you try seeing if it doesn't work with both methods?

**Comment by TaunT** [comment]
> I noticed the project file you sent this time wasn't ballooned in size. Is that no longer a problem or was it just a problem with a specific file?

I don't know what it depends on, that file was really small, but only the last 15-17 MB
[RCO189_ctpr.zip](https://github.com/user-attachments/files/17905068/RCO189_ctpr.zip)


> Also, how are you trying to export this to an image (the button for a the single file download or the one that exports everything to a zip?). Can you try seeing if it doesn't work with both methods?

I tried saving it in zip now, inside there is a picture with the same non-bold font)
