### ISSUE TITLE
Various situations occasionally produce the ['NoneType' object has no attribute 'isupper' error.]

### ISSUE THREAD

**Issue by sweetburble** [ogkalu2/comic-translate#237]
This error occurs sporadically when processing dozens of images. To reproduce the error, manual testing was conducted.

Depending on the OCR or Translator being used, this error sometimes appears and sometimes doesn't.

The error log is as follows.
```
Traceback:
  File "C:\Users\Bandi\Desktop\comic-translate\app\thread_worker.py", line 30, in run
  File "C:\Users\Bandi\Desktop\comic-translate\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bandi\Desktop\comic-translate\controller.py", line 469, in <lambda>
    lambda: self.pipeline.translate_image(single_block),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bandi\Desktop\comic-translate\pipeline.py", line 133, in translate_image        
    set_upper_case(self.main_page.blk_list, upper_case)
  File "C:\Users\Bandi\Desktop\comic-translate\modules\utils\translator_utils.py", line 68, in set_upper_case
    elif not upper_case and translation.isupper():
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isupper'
```

OR
```
Traceback:
Traceback (most recent call last):
  File "C:\Users\Bandi\Desktop\comic-translate\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bandi\Desktop\comic-translate\pipeline.py", line 314, in batch_process
    format_translations(blk_list, trg_lng_cd, upper_case=upper_case)
  File "C:\Users\Bandi\Desktop\comic-translate\modules\utils\translator_utils.py", line 97, in format_translations
    set_upper_case(blk_list, upper_case)
  File "C:\Users\Bandi\Desktop\comic-translate\modules\utils\translator_utils.py", line 68, in set_upper_case
    elif not upper_case and translation.isupper():
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isupper'
```

Your project is so great, it's being used frequently!

**Comment by ogkalu2** [comment]
Fixed

**Comment by theprasant** [comment]
> Fixed

Hi, I'm still getting the error
```
An error occurred:
NameError: cannot access free variable 'trg_lng_cd' where it is not associated with a value in enclosing scope

Traceback:
Traceback (most recent call last):
  File "C:\myData\others\comic-translate\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\myData\others\comic-translate\pipeline\main_pipeline.py", line 112, in webtoon_batch_process
    return self.webtoon_batch_processor.webtoon_batch_process(selected_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\myData\others\comic-translate\pipeline\webtoon_batch_processor.py", line 1073, in webtoon_batch_process
    self._finalize_and_emit_for_virtual_page(vpage)
  File "C:\myData\others\comic-translate\pipeline\webtoon_batch_processor.py", line 822, in _finalize_and_emit_for_virtual_page
    self._emit_and_store_virtual_page_results(vpage, merged_blocks)
  File "C:\myData\others\comic-translate\pipeline\webtoon_batch_processor.py", line 738, in _emit_and_store_virtual_page_results
    if any(lang in trg_lng_cd.lower() for lang in ['zh', 'ja', 'th']):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\myData\others\comic-translate\pipeline\webtoon_batch_processor.py", line 738, in <genexpr>
    if any(lang in trg_lng_cd.lower() for lang in ['zh', 'ja', 'th']):
                   ^^^^^^^^^^
NameError: cannot access free variable 'trg_lng_cd' where it is not associated with a value in enclosing scope
```

<img width="628" height="328" alt="Image" src="https://github.com/user-attachments/assets/13fc45bd-bc74-48cc-85f7-73e8842f4faf" />

There were a total of 47 images in the zip file.
When I set it to `Automatic` and clicked the `Translate All`, it showed the error after cleaning the text of the 1st image.

```
Windows 11, Using GPU, Translating from the Chinese language
```

Last time I tested with only 1  image, and it worked fine.
